### ISSUE TITLE
No matches attempting to identify the disc image 

### ISSUE THREAD

**Issue by Hackinside** [trapexit/3dt#21]
**VizHouse - 3DO M2 Kiosk**

```
- volume_unique_identifier: 0x034AB95B
 - volume_block_count: 30720
 - root_unique_identifier: 0x3CE7F390
 - file_count: 2244
 - total_data_size: 17647937
 - no_matches:
```

**Polystar - Konami M2 Arcade**

```
- volume_unique_identifier: 0x147F435A
 - volume_block_count: 11776
 - root_unique_identifier: 0x1BD9933E
 - file_count: 33
 - total_data_size: 20039490
 - no_matches:
```
